attack:
    epsilon: 16
    steps: 100
    input_size: 512
    mode: sds
    img_path: test_images/to_protect
    output_path: out/
    alpha: 1
    g_mode: "-"
    use_wandb: False
    project_name: iclr_mist
    diff_pgd: [False, 0.2, 'ddim100'] # un-used feature
    using_target: False
    target_rate: 5
    device: 0
    max_exp_num: 100
